name: Build and Publish to NPM

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Install dependencies
        working-directory: ./uz-workspace
        run: npm i
        
      - name: Build Universal Zone
        working-directory: ./uz-workspace
        run: npm run build:uz
      
      - name: Build Ionic Zone
        working-directory: ./uz-workspace
        run: npm run build:ionic
        
      - name: Upload Universal Zone artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ngx-universal-zone
          path: ./uz-workspace/dist/ngx-universal-zone
          
      - name: Upload Ionic Zone artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ngx-ionic-zone
          path: ./uz-workspace/dist/ngx-ionic-zone

  publish:
    needs: build
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'
          
      - name: Download Universal Zone artifacts
        uses: actions/download-artifact@v4
        with:
          name: ngx-universal-zone
          path: ./ngx-universal-zone
          
      - name: Download Ionic Zone artifacts
        uses: actions/download-artifact@v4
        with:
          name: ngx-ionic-zone
          path: ./ngx-ionic-zone
          
      - name: Publish Universal Zone to NPM
        working-directory: ./ngx-universal-zone
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: '${{ secrets.NPM_TOKEN }}'
          
      - name: Publish Ionic Zone to NPM
        working-directory: ./ngx-ionic-zone
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: '${{ secrets.NPM_TOKEN }}'
